config/routes.rb
Rails.application.routes.draw do
  resources :lista_consultas
  resources :consultas
  resources :tipo_consultas
  resources :paciente_consultas, only: [:index, :destroy]
  resources :pacientes
  resources :usuarios
  resources :sessao_usuarios, only: [:create, :new, :destroy]
  resources :sessao_pacientes, only: [:create, :login, :destroy]

  get 'pacientes/lista' => 'pacientes#index'
  match '/sessao_pacientes/loginComHashCPF' => 'sessao_pacientes#loginComHashCPF', via: [:get, :post]
  match '/sessao_pacientes' => 'sessao_pacientes#login', via: [:get, :post]
  match '/paciente_consultas/getFila' => 'paciente_consultas#getFila', via: [:get, :post]
  match '/paciente_consultas/getData' => 'paciente_consultas#getData', via: [:get, :post]
  match '/atendimento' => 'lista_consultas#atendimento', via: [:get, :post]
  match '/chamar' => 'consultas#chamar', via: [:get, :post]
  match '/dispensar' => 'consultas#dispensar', via: [:get, :post]
  match '/desmarcar' => 'consultas#desmarcar', via: [:get, :post]
  match '/atualizar' => 'paciente_consultas#atualizar', via:[:get,:post]

  root 'sessao_usuarios#new'

end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
	enum prioridade: {normal: 0, idoso: 1, gestante: 2, deficiente: 3, crianca_de_colo: 4}
	scope :most_recent, -> { order('created_at DESC') }
    validates :nome, :cpf, presence: true
	validates :cpf, uniqueness: {message: "já exite!"}, 
					numericality: {message: 'deve ser um número'},
					length: { is: 11 } 
	belongs_to :consulta
	paginates_per 5

	# @@base_uri = 'https://teste-fcda1.firebaseio.com/'
	# @@secret_key = 'AIzaSyCuJAiJ_3oQ0C7oxTUJKSkYnp-JQtft-Ew'
	# @@to = "eqFTAv40ITI:APA91bFYASO3Nq1K-1la8QSoWD-Iipxvd_Pk1KbWht3LqRVAgj5nFEuyjo3cCvPww252AUQd2yvEkUuUxeNgnX8iID1TennTd4aBhfAX8ePmIInk43fw6WKy6C6ICU2lXYNoig0BUhjc"

	def self.search(query)
  		if query.present?
  			find_by(['nome LIKE :query OR
  				cpf LIKE :query', query: "#{query}"])
  		end
	end

	def self.authenticate(cpf)
		cpf = cpf.tr('.','')
		cpf = cpf.tr('-','')
		hashcpf = Digest::SHA256.hexdigest cpf
		paciente = find_by(hashcpf: hashcpf)
    end

	# def fireBaseNotify
	# 	firebase = Firebase::Client.new(base_uri, secret_key)
	# 	response = firebase.push(
	# 		"notification" => { 
	# 			:body => "Pick the milk",
	# 			:title => "Fila de Atendimento",
	# 			:sound => "default",
	# 			:priority => "high" 
	# 		}, "data" => {:id => 9} , 
	# 		"to"=> Paciente.to)
	# end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :autenticacao_requerida, except: [:getId]
  before_action :nivel_auxiliar, except: [:getId]
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  # GET /pacientes
  # GET /pacientes.json
  def index
    @info = params[:info]
    if(@info == nil)
	    @pacientes = Paciente.most_recent.page params[:page]
    else
       @pacientes = Paciente.where('nome like ? OR cpf like ?', "%#{@info}%", "%#{@info}%").most_recent.page params[:page]
    end

  end

  # GET /pacientes/1
  # GET /pacientes/1.json
  def show
	 @paciente = Paciente.find(params[:id])
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
  end

  # GET /pacien/1/edit
  def edit
  end

  # POST /pacientes
  # POST /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)
    @paciente.hashcpf = Digest::SHA256.hexdigest @paciente.cpf
    respond_to do |format|
      if @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1
  # PATCH/PUT /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        @paciente.hashcpf = Digest::SHA256.hexdigest @paciente.cpf
        @paciente.save
        format.html { redirect_to @paciente, notice: 'Paciente foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1
  # DELETE /pacientes/1.json
  def destroy
	@consultas = Consulta.where(paciente_id: params[:id])
	@consultas.each do |c|
		c.destroy
		c.save
	end
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paciente_params
      params.require(:paciente).permit(:nome, :cpf, :prioridade, :hashcpf, :telefone)
	end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_form.html.erb
<script>
  $(document).ready(function() {
      $('select').material_select();
  });
</script>
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content white-text">
        <%= form_for(@paciente) do |f| %>
          <% if @paciente.errors.any? %>
            <div id="error_explanation">
              <ul>
                <% @paciente.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="input-field labelEsquerda">
            <%= f.text_field :nome, placeholder: "Nome" %>
          </div>
          <div class="input-field labelEsquerda">
            <%= f.text_field :cpf, placeholder: "Cpf" %>
          </div>

          <div class="input-field labelEsquerda">
            <%= f.label :prioridade %><br>
            <%= select(:paciente, :prioridade, [['Normal', 'normal'], ['Idoso', 'idoso'], ['Gestante', 'gestante'], ['Deficiente', 'deficiente'], ['Criança de Colo', 'crianca_de_colo']],
             { include_blank: false }) %>
          </div>

          <div class="input-field labelEsquerda">
            <%= f.text_field :telefone, placeholder: "Telefone" %>
          </div>

          <div class="actions">
            <%= f.submit nil, class:  "waves-effect waves-light btn"%>
            <%= link_to t('links.back'), pacientes_path, class:  "waves-effect waves-light btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pacientes/edit.html.erb
<h1>Editando Paciente</h1>

<%= render 'form' %>
<%= link_to t('links.show'), @paciente, class:  "waves-effect waves-light btn"  %>

app/views/pacientes/index.html.erb
<h1>Lista de Pacientes</h1>
<form method="get" action="pacientes">
	<input type="text" id="datepicke" name="info" placeholder="Nome, CPF" autofocus>
</form>
<div id="padd">
  <%= link_to 'Novo Paciente', new_paciente_path, class:  "waves-effect waves-light btn"  %>
</div>
<% @pacientes.each do |f| %>
<div class="row">
  <div class="col s12">
		<div class="card">
			<div class="card-content white-text">
        <span class="card-title">Paciente: <%= f.nome %></span>
				<table class="striped">
					<thead>
						<tr>
							<th class="center-align">Cpf</th>
							<th class="center-align">Prioridade</th>
							<th class="center-align">Telefone</th>
							<th colspan="3"></th>
						</tr>
						</thead>

						<tbody>
							<tr>
								<td class="center-align"><%= f.cpf %></td>
								<td class="center-align"><%= f.prioridade %></td>
								<td class="center-align"><%= f.telefone %></td>
                <td class="center-align"><%= link_to "Nova Consulta", url_options = { :controller => "consultas",
                   :action => "new", :q => f.cpf}, html_options = { class: "waves-effect waves-light btn"} %></td>
							</tr>
							<tr>
                <td class="center-align"><%= link_to t('links.show'), f, class: "waves-effect waves-light btn"%></td>
								<td class="center-align"><%= link_to t('links.edit'), edit_paciente_path(f), class: "waves-effect waves-light btn"%></td> 
								<td class="center-align"><%= link_to t('links.destroy'), f, method: :delete, 
                      data: { confirm: 'Essa ação apagara todas as consultas que esse usuário estiver! Tem certeza? ' }, 
                      class: "waves-effect waves-light btn"%></td>
                      class:  "waves-effect waves-light btn" %></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
</div>
<% end %>

<%= paginate @pacientes %>

app/views/pacientes/new.html.erb
<h1>Novo Paciente</h1>

<%= render 'form' %>

app/views/pacientes/show.html.erb
<div class="row">
  <div class="col s12">
        <h1>Paciente</h1>
		<div class="card">
			<div class="card-content white-text">
        		<span class="card-title"><%= @paciente.nome %></span>
				<table class="striped">
					<thead>
						<tr>
							<th>Cpf</th>
							<th>Prioridade</th>
							<th>Telefone</th>
						</tr>
						</thead>

						<tbody>
							<tr>
								<td><%= @paciente.cpf %></td>
								<td><%= @paciente.prioridade %></td>
								<td><%= @paciente.telefone %></td>
                                <td><%= link_to "Nova Consulta", url_options = { :controller => "consultas",
                                    :action => "new", :q => @paciente.cpf}, html_options = { class: "waves-effect waves-light btn"}%></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
</div>

<%= link_to t('links.edit'), edit_paciente_path(@paciente), class: "waves-effect waves-light btn"%>
<%= link_to t('links.back'), pacientes_path, class: "waves-effect waves-light btn"%>