config/routes.rb
Rails.application.routes.draw do
  resources :lista_consultas
  resources :consultas
  resources :tipo_consultas
  resources :paciente_consultas, only: [:index, :destroy]
  resources :pacientes
  resources :usuarios
  resources :sessao_usuarios, only: [:create, :new, :destroy]
  resources :sessao_pacientes, only: [:create, :login, :destroy]

  get 'pacientes/lista' => 'pacientes#index'
  match '/sessao_pacientes/loginComHashCPF' => 'sessao_pacientes#loginComHashCPF', via: [:get, :post]
  match '/sessao_pacientes' => 'sessao_pacientes#login', via: [:get, :post]
  match '/paciente_consultas/getFila' => 'paciente_consultas#getFila', via: [:get, :post]
  match '/paciente_consultas/getData' => 'paciente_consultas#getData', via: [:get, :post]
  match '/atendimento' => 'lista_consultas#atendimento', via: [:get, :post]
  match '/chamar' => 'consultas#chamar', via: [:get, :post]
  match '/dispensar' => 'consultas#dispensar', via: [:get, :post]
  match '/desmarcar' => 'consultas#desmarcar', via: [:get, :post]
  match '/atualizar' => 'paciente_consultas#atualizar', via:[:get,:post]

  root 'sessao_usuarios#new'

end

app/models/tipo_consulta.rb
class TipoConsulta < ActiveRecord::Base
	validates :nome, :duracao, presence: true
	belongs_to :consulta
end

app/controllers/tipo_consultas_controller.rb
class TipoConsultasController < ApplicationController
  before_action :autenticacao_requerida
  before_action :nivel_auxiliar
  before_action :set_tipo_consulta, only: [:show, :edit, :update, :destroy]

  # GET /tipo_consultas
  # GET /tipo_consultas.json
  def index
    @tipo_consultas = TipoConsulta.all
  end

  # GET /tipo_consultas/1
  # GET /tipo_consultas/1.json
  def show
  end

  # GET /tipo_consultas/new
  def new
    @tipo_consulta = TipoConsulta.new
  end

  # GET /tipo_consultas/1/edit
  def edit
  end

  # POST /tipo_consultas
  # POST /tipo_consultas.json
  def create
    @tipo_consulta = TipoConsulta.new(tipo_consulta_params)

    respond_to do |format|
      if @tipo_consulta.save
        format.html { redirect_to @tipo_consulta, notice: "Tipo consulta: #{@tipo_consulta.nome} foi criado com sucesso." }
        format.json { render :show, status: :created, location: @tipo_consulta }
      else
        format.html { render :new }
        format.json { render json: @tipo_consulta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_consultas/1
  # PATCH/PUT /tipo_consultas/1.json
  def update
    respond_to do |format|
      if @tipo_consulta.update(tipo_consulta_params)
        format.html { redirect_to @tipo_consulta, notice: "Tipo consulta: #{@tipo_consulta.nome} foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @tipo_consulta }
      else
        format.html { render :edit }
        format.json { render json: @tipo_consulta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_consultas/1
  # DELETE /tipo_consultas/1.json
  def destroy
    @tipo_consulta.destroy
    respond_to do |format|
      format.html { redirect_to tipo_consultas_url, notice: "Tipo consulta: #{@tipo_consulta.nome} foi apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_consulta
      @tipo_consulta = TipoConsulta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_consulta_params
      params.require(:tipo_consulta).permit(:nome, :duracao)
    end
end

app/helpers/tipo_consultas_helper.rb
module TipoConsultasHelper
end

app/views/tipo_consultas/_form.html.erb
<script>
  $(document).ready(function() {
      $('select').material_select();
  });
</script>
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content white-text">
        <%= form_for(@tipo_consulta) do |f| %>
          <% if @tipo_consulta.errors.any? %>
            <div id="error_explanation">
              <ul>
                <% @tipo_consulta.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="input-field labelEsquerda">
            <%= f.text_field :nome, placeholder: "Nome" %>
          </div>
          <div class="input-field labelEsquerda" id="time">
            <%= f.label :duracao %><br>
            <%= f.time_select :duracao, :time_separator => "" %>
          </div>
          <div class="actions">
            <div class="waves-effect waves-light btn"> <%= f.submit %> </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tipo_consultas/edit.html.erb
<h1>Editando Tipo de Consulta</h1>

<%= render 'form' %>

<%= link_to t('links.show'), @tipo_consulta, class:  "waves-effect waves-light btn"  %>
<%= link_to t('links.back'), tipo_consultas_path, class:  "waves-effect waves-light btn"  %>

app/views/tipo_consultas/index.html.erb
<h1>Tipos de Consultas</h1>

<div class="waves-effect waves-light btn"><%= link_to 'Novo Tipo de consulta', new_tipo_consulta_path %></div>
<div class="row">
	<div class="col s12">
		<div class="card">
			<div class="card-content white-text">
				<table class="striped">
					<thead>
						<tr>
							<th>Nome</th>
							<th>Duracao</th>
						</tr>
					</thead>
					<tbody>
						<% @tipo_consultas.each do |tipo_consulta| %>
						<tr>
							<td><%= tipo_consulta.nome %></td>
							<td><%= tipo_consulta.duracao.strftime("%H:%M") %></td>
							<td><%= link_to t('links.show'), tipo_consulta, class: "waves-effect waves-light btn"%></td>
							<td><%= link_to t('links.edit'), edit_tipo_consulta_path(tipo_consulta), class: "waves-effect waves-light btn"%></td>
							<td><%= link_to t('links.destroy'), tipo_consulta, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "waves-effect waves-light btn"%></td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/tipo_consultas/new.html.erb
<h1>Novo Tipo de Consulta</h1>

<%= render 'form' %>

<%= link_to t('links.back'), tipo_consultas_path, class:  "waves-effect waves-light btn"  %>

app/views/tipo_consultas/show.html.erb
<div class="row">
	<div class="col s12">
		<div class="card">
			<div class="card-content white-text">
				<table class="striped">
					<thead>
						<tr>
							<th>Nome</th>
							<th>Duracao</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><%= @tipo_consulta.nome %></td>
							<td><%= @tipo_consulta.duracao.strftime("%H:%M") %></td>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<%= link_to t('links.edit'), edit_tipo_consulta_path(@tipo_consulta), class:  "waves-effect waves-light btn"  %>
<%= link_to t('links.back'), tipo_consultas_path, class:  "waves-effect waves-light btn"  %>