config/routes.rb
Rails.application.routes.draw do
  resources :lista_consultas
  resources :consultas
  resources :tipo_consultas
  resources :paciente_consultas, only: [:index, :destroy]
  resources :pacientes
  resources :usuarios
  resources :sessao_usuarios, only: [:create, :new, :destroy]
  resources :sessao_pacientes, only: [:create, :login, :destroy]

  get 'pacientes/lista' => 'pacientes#index'
  match '/sessao_pacientes/loginComHashCPF' => 'sessao_pacientes#loginComHashCPF', via: [:get, :post]
  match '/sessao_pacientes' => 'sessao_pacientes#login', via: [:get, :post]
  match '/paciente_consultas/getFila' => 'paciente_consultas#getFila', via: [:get, :post]
  match '/paciente_consultas/getData' => 'paciente_consultas#getData', via: [:get, :post]
  match '/atendimento' => 'lista_consultas#atendimento', via: [:get, :post]
  match '/chamar' => 'consultas#chamar', via: [:get, :post]
  match '/dispensar' => 'consultas#dispensar', via: [:get, :post]
  match '/desmarcar' => 'consultas#desmarcar', via: [:get, :post]
  match '/atualizar' => 'paciente_consultas#atualizar', via:[:get,:post]

  root 'sessao_usuarios#new'

end

app/models/consulta.rb
class Consulta < ActiveRecord::Base
	enum status: {espera: 0, atendimento: 1, atendido: 2, cancelado: 3}
	scope :most_recent, -> { order('created_at DESC') }
	validates :inicio, :data, presence: true
	validates :paciente_nome , presence: {message: "não pode ficar em branco, faça uma busca!"}
	has_many :tipo_consultas
	has_one :pacientes
	belongs_to :lista_consulta
	paginates_per 5
end

app/controllers/consultas_controller.rb
class ConsultasController < ApplicationController
  before_action :autenticacao_requerida
  before_action :nivel_auxiliar, except: [:chamar, :dispensar]
  before_action :set_consulta, only: [:show, :edit, :update, :destroy]

  # GET /consultas
  # GET /consultas.json
  def index
    if (paciente_logado?)
      redirect_to paciente_consultas_path
    end

    @info = params[:info]
    if(@info == nil)
      @consultas = Consulta.most_recent.page params[:page]
    else
      @pacientes = Paciente.where('nome like ? OR cpf like ?', "%#{@info}%", "%#{@info}%")
      puts @pacientes
      @consultas = Consulta.where(paciente_id: @pacientes.each { |p| p.id}).most_recent.page params[:page]
    end
  end

  def chamar
	  @c = Consulta.find(params[:consulta])
	  @atendimento = Consulta.find_by(status: 1)
	  @tempo = Time.now - 3.hour
	  if (@atendimento != nil)
		  @atendimento.atendido!
		  @atendimento.fim = @tempo
		  @atendimento.save
	  end
    if @c.status == 'espera'
      @c.inicio = @tempo
      @c.fim = ConsultasHelper.getFimConsulta(@c)
      @c.atendimento!
      ConsultasHelper.atualizarHorarios
      ConsultasHelper.calcularMedia(@c.tipo_consulta)
      redirect_to atendimento_path
    else
      redirect_to atendimento_path, notice: 'Esse paciente não está mais em espera.'
    end
  end

  def dispensar
	  @c = Consulta.find(params[:consulta])

	  @c.atendido!
	  @c.fim = Time.now - 3.hour
	  @c.save
	  ConsultasHelper.calcularMedia(@c.tipo_consulta)
	  redirect_to atendimento_path, notice: "Duração: #{@c.fim.min - @c.inicio.min} minuto(s)"
  end

  def desmarcar
	  @c = Consulta.find(params[:consulta])
	  @c.cancelado!
	  redirect_to consulta_path(@c), notice: 'Consulta desmarcada com sucesso.'
  end

  # GET /consultas/1
  # GET /consultas/1.json
  def show
  end

  # GET /consultas/new
  def new
    @search_query = params[:q]
    @search_query = @search_query.strip if @search_query != nil
    @paciente = Paciente.search(@search_query)
    @consulta = Consulta.new
    if @paciente != nil
      @consulta.paciente_nome = @paciente.nome
    end

    if ListaConsultasHelper.getDate(Date.current).empty?
  	  @consulta.inicio = Time.new.change(hour: 8)
    elsif Consulta.where(data: Date.current).where(status: 0).last == nil
      @consulta.inicio = Time.current
  	else
  	  @consulta.inicio = Consulta.where(data: Date.current).where(status: 0).order(:inicio).last.fim
 	end
  end

  # GET /consultas/1/edit
  def edit
    @search_query = params[:q]
    @search_query = @search_query.strip if @search_query != nil
    @paciente = Paciente.search(@search_query)
    if @paciente != nil
      @consulta.paciente_nome = @paciente.nome
    end
  end

  # POST /consultas
  # POST /consultas.json
  def create
    @consulta = Consulta.new(consulta_params)
    @consulta.paciente_id = ConsultasHelper.getIdPaciente(@consulta.paciente_nome)
  	@consulta.tipo_consulta_id = params[:tipo_consulta][:tipo_consulta_id]
  	@consulta.duracao = ConsultasHelper.getDuracaoConsulta(@consulta.tipo_consulta_id)
  	@consulta.tipo_consulta = ConsultasHelper.getNomeTipoConsulta(@consulta.tipo_consulta_id)
	  @consulta.numeroFila = ConsultasHelper.getNumFila()
	  @consulta.fim = ConsultasHelper.getFimConsulta(@consulta)

    respond_to do |format|
      if @consulta.save
        format.html { redirect_to @consulta, notice: 'Consulta foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @consulta }
      else
        format.html { render :new }
        format.json { render json: @consulta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultas/1
  # PATCH/PUT /consultas/1.json
  def update
    @consulta.paciente_id = ConsultasHelper.getIdPaciente(@consulta.paciente_nome)
  	@consulta.tipo_consulta_id = params[:tipo_consulta][:tipo_consulta_id]
  	@consulta.duracao = ConsultasHelper.getDuracaoConsulta(@consulta.tipo_consulta_id)
  	@consulta.tipo_consulta = ConsultasHelper.getNomeTipoConsulta(@consulta.tipo_consulta_id)
	  @consulta.numeroFila = ConsultasHelper.getNumFila()
    respond_to do |format|
      if @consulta.update(consulta_params)
        @consulta.fim = ConsultasHelper.getFimConsulta(@consulta)
        @consulta.update(consulta_params)
        format.html { redirect_to @consulta, notice: 'Consulta foi atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @consulta }
      else
        format.html { render :edit }
        format.json { render json: @consulta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultas/1
  # DELETE /consultas/1.json
  def destroy
    @consulta.destroy
    respond_to do |format|
      format.html { redirect_to consultas_url, notice: 'Consulta foi apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consulta
      @consulta = Consulta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consulta_params
      params.require(:consulta).permit(:inicio, :fim, :duracao, :data, :status, :numeroFila, :paciente_nome, :tipo_consulta)
    end
end

app/helpers/consultas_helper.rb
module ConsultasHelper
	# Busca nome do paciente para colocar na consulta
	def self.getIdPaciente(n)
		if(n != "")
			@p = Paciente.find_by(nome: n)
			@p.id
		end
	end

	def getIdPaciente(n)
		ConsultasHelper(n)
	end

	# Busca o nome do tipo da consulta
	def self.getNomeTipoConsulta(tc)
		@p = TipoConsulta.find_by(id: tc)
		@p.nome
	end

	def getNomeTipoConsulta(tc)
		ConsultasHelper(tc)
	end

	# Busca a duração do tipo da consulta
	def self.getDuracaoConsulta(dtc)
		@p = TipoConsulta.find_by(id: dtc)
		@p.duracao
	end

	def getDuracaoConsulta(tc)
		ConsultasHelper(tc)
	end

	# Busca a duração do tipo da consulta
	def self.getFimConsulta(c)
		f = c.inicio
		f + c.duracao.strftime("%H").to_i.hour + c.duracao.strftime("%M").to_i.minutes
	end

	def getFimConsulta(c)
		ConsultasHelper(c)
	end


	# Gera número fila
	def self.getNumFila()
		if Consulta.last != nil
			Consulta.last.numeroFila + 1000
		else
			1000
		end
	end

	def getNumFila()
		ConsultasHelper()
	end

	# Gera número fila
	def self.calcularMedia(tc)
		at = Consulta.where(data: Date.current, tipo_consulta: tc, status: 2)
		if at.size != 0
			minutos = 0
			at.each do |t|
				k = (t.fim.min - t.inicio.min)
				if k < 0
					k = k + 60
				end
				minutos =  minutos + k
			end
			hora = 0
			minutos = minutos/at.size
			if(minutos > 60)
				hora = minutos/60
				minutos = minutos % 60
			end
			if(minutos < 0)
				minutos = 0
			end
			t = TipoConsulta.find_by(nome: tc)
			t.duracao = Time.new(2000,01,01,hora,minutos,0, "-00:00")
			t.save
			rest = Consulta.where(data: Date.current, tipo_consulta: tc, status: 1)
			rest.each do |r|
				r.duracao = Time.new(2000,01,01,hora,minutos,0, "-00:00")
				r.save
			end
		end
	end

	def calcularMedia(tc)
		ConsultasHelper(tc)
	end

	def self.atualizarHorarios()
		es = Consulta.where(data: Date.current, status: 0).order(:inicio)
		at = Consulta.find_by(status: 1)
		duracao = Time.new(2001,01,01,00,00,00)
		if es.size != 0
			es.each do |e|
				e.inicio = at.fim + duracao.strftime("%H").to_i.hour + duracao.strftime("%M").to_i.minutes
				e.fim = getFimConsulta(e)
				e.save
				duracao = duracao + e.duracao.strftime("%H").to_i.hour + e.duracao.strftime("%M").to_i.minutes
			end
		end
	end

	def atualizarHorarios()
		ConsultasHelper()
	end
end

app/views/consultas/_buscaPaciente.html.erb
<%= form_for consultas_path, method: :get, class: 'search' do |q| %>
    <%= text_field_tag :q, params[:q], placeholder: "Buscar Paciente", autofocus: true %>
    <%= q.submit "Buscar", :class => 'waves-effect waves-light btn' %><br>
<% end %>

app/views/consultas/_form.html.erb
<script>
	$(document).ready(function() {
	    $('select').material_select();
	  });
</script>

<%= render 'buscaPaciente' %>

<div class="row">
	<div class="col s12">
		<div class="card">
			<div class="card-content white-text">
				<%= form_for(@consulta) do |f| %>
					<% if @consulta.errors.any? %>
						<div id="error_explanation">
							<ul>
								<% @consulta.errors.full_messages.each do |message| %>
									<li><%= message %></li>
								<% end %>
							</ul>
						</div>
					<% end %>

					<div class="input-field">
						<%= f.text_field :paciente_nome, placeholder: "Nome do Paciente" %>
					</div>

					<div class="input-field labelEsquerda" id="time">
						<%= f.label :inicio  %>
						<%= f.time_select :inicio, :time_separator => "" %>
					</div>

					<div class="input-field labelEsquerda">
						<%= f.label :data %>
						<%= f.date_select :data %>
					</div>

	  				<div class="input-field labelEsquerda">
						<%= f.label :tipo_da_consulta %>
		 				<%= select("tipo_consulta", "tipo_consulta_id", TipoConsulta.all.collect {|p| [ p.nome, p.id ] }, { include_blank: false }) %>
	  				</div>

	  				<div class="actions">
						<%= f.submit nil, class: "waves-effect waves-light btn" %>
	 				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/consultas/edit.html.erb
<h1>Editando Consulta</h1>

<%= render 'form' %>

<%= link_to t('links.show'), @consulta, class:  "waves-effect waves-light btn" %>
<%= link_to t('links.back'), consultas_path, class:  "waves-effect waves-light btn" %>

app/views/consultas/index.html.erb
<h1>Lista de Consultas</h1>
<form method="get" action="consultas">
	<input type="text" id="datepicke" name="info" placeholder="Nome, CPF" autofocus>
</form>
<div id="padd">
    <%= link_to 'Nova Consulta', new_consulta_path, class:  "waves-effect waves-light btn"%>
    <%= link_to 'Novo Tipo de Consulta', new_tipo_consulta_path, class:  "waves-effect waves-light btn" %>
</div>

<% @consultas.each do |c| %><div class="row">
	<div class="col s12">
		<div class="card">
			<div class="card-content white-text">
				<table class="striped">
					<thead>
						<span>Paciente: <%= c.paciente_nome %></span>
						<tr>
							<th>Data</th>
							<th>Inicio</th>
							<th>Fim</th>
							<th>Duração</th>
							<th>Tipo da Consulta</th>
						</tr>
						</thead>

						<tbody>
							<tr>
								<td><%= c.data.strftime("%d/%m/%Y") %></td>
								<td><%= c.inicio.strftime("%H:%M") %></td>
								<td><%= c.fim.strftime("%H:%M") %></td>
								<td><%= c.duracao.strftime("%H:%M") %></td>
								<td><%= c.tipo_consulta %></td>
							</tr>
							<tr>
								<td><%= link_to t('links.show'), c, class:  "waves-effect waves-light btn"%></td> 
								<td><%= link_to t('links.edit'), edit_consulta_path(c), class:  "waves-effect waves-light btn"%></td>  
								<td><%= link_to t('links.destroy'), c, method: :delete,  data: { confirm: 'Você tem certeza?' }, 
								class:  "waves-effect waves-light btn" %></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
<% end %>
<%= paginate @consultas %>

app/views/consultas/new.html.erb
<h1>Nova Consulta</h1>

<%= render 'form' %>

<%= link_to t('links.back'), consultas_path, class:  "waves-effect waves-light btn" %>

app/views/consultas/show.html.erb
<div class="col s12">
	<div class="card">
		<div class="card-content white-text">
			<span class="card-title">Paciente: <%= @consulta.paciente_nome %> </span>
			<table class="striped">
				<thead>
				<tr>
					<th>Data</th>
					<th>Tipo da Consulta</th>
        		    <th>Inicio</th>
            		<th>Fim</th>
              		<th>Duração</th>
				</tr>
				</thead>

				<tbody>
					<tr>
						<td><%= @consulta.data %></td>
						<td><%= @consulta.tipo_consulta %></td>
						<td><%= @consulta.inicio.strftime("%H:%M")%></td>
						<td><%= @consulta.fim.strftime("%H:%M")%></td>
						<td><%= @consulta.duracao.strftime("%H:%M")%></td>
					</tr>
					<tr>
						<td><%= link_to 'Editar', edit_consulta_path(@consulta), class: "waves-effect waves-light btn" %></td> 
						<td><%= link_to 'Consultas', consultas_path, class:  "waves-effect waves-light btn" %></td>
						<% if @consulta.status == "espera" %>  
							<td><%= link_to 'Desmarcar', {:controller => "consultas", :action => "desmarcar", :consulta => @consulta},
							 data: { confirm: 'Você tem certeza?'}, class: "waves-effect waves-light btn"%></td>
						<% end %>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

<%= link_to 'Lista de Consultas', lista_consultas_path, class:  "waves-effect waves-light btn" %>