config/routes.rb
Rails.application.routes.draw do
  resources :lista_consultas
  resources :consultas
  resources :tipo_consultas
  resources :paciente_consultas, only: [:index, :destroy]
  resources :pacientes
  resources :usuarios
  resources :sessao_usuarios, only: [:create, :new, :destroy]
  resources :sessao_pacientes, only: [:create, :login, :destroy]

  get 'pacientes/lista' => 'pacientes#index'
  match '/sessao_pacientes/loginComHashCPF' => 'sessao_pacientes#loginComHashCPF', via: [:get, :post]
  match '/sessao_pacientes' => 'sessao_pacientes#login', via: [:get, :post]
  match '/paciente_consultas/getFila' => 'paciente_consultas#getFila', via: [:get, :post]
  match '/paciente_consultas/getData' => 'paciente_consultas#getData', via: [:get, :post]
  match '/atendimento' => 'lista_consultas#atendimento', via: [:get, :post]
  match '/chamar' => 'consultas#chamar', via: [:get, :post]
  match '/dispensar' => 'consultas#dispensar', via: [:get, :post]
  match '/desmarcar' => 'consultas#desmarcar', via: [:get, :post]
  match '/atualizar' => 'paciente_consultas#atualizar', via:[:get,:post]

  root 'sessao_usuarios#new'

end

app/views/layouts/_paciente_navbar.html.erb
<li title="Sair"><%= link_to '<i class="fa fa-sign-out" aria-hidden="true" id="iconNav"></i>'.html_safe, 
              sessao_paciente_path(paciente_atual.id), class: "brand-logo right", method: :delete %></li>
<li title="Atualizar"><%= link_to '<i class="fa fa-refresh" aria-hidden="true" id="iconNav"></i>'.html_safe, atualizar, class: "brand-logo right", style: 'margin-right: 14%;' %></li>

app/views/layouts/_user_navbar.html.erb
<% if current_page?(:controller => 'lista_consultas', :action => 'atendimento') %>
<div class="hoverable"><li><%= link_to "Atendimento", atendimento_path %></li>
  <% end %>
  <% if request.path.include? "pacientes" or request.path.include? "prioridades" or request.path.include? "lista_consultas" or request.path.include? "consultas"%>
  <li><%= link_to "Lista De Consultas", lista_consultas_path %></li>
  <li> <%= link_to "Pacientes", pacientes_path %></li>
  <li> <%= link_to "Consultas", consultas_path %></li>
  <% end %>
  <% if request.path.include? "usuarios" %>
  <% if usuario_atual.nivel == "auxiliar" %>
  <li><%= link_to "Lista De Consultas", lista_consultas_path %></li>
  <% else %>
  <li><%= link_to "Atendimento", atendimento_path %></li>
  <% end %>
  <% end %>
  <li title="Perfil"><%= link_to '<i class="fa fa-user" aria-hidden="true" id="iconNav"></i>'.html_safe, usuario_path(usuario_atual.id), 
    class: "brand-logo right", style: 'margin-right: 4%;' %></li>
    <li title="Sair"><%= link_to '<i class="fa fa-sign-out" aria-hidden="true" id="iconNav"></i>'.html_safe, 
      sessao_usuario_path(usuario_atual.id), class: "brand-logo right", method: :delete %></li>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<head>
 <title>Ortodontia - Estetica </title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
 <link rel="stylesheet" href="/vendor/assets/stylesheets/btn.responsive.css">
</head>
<body>
  <div class="row" id="inicio">
    <nav>
      <div class="nav-w">      
        <ul>
         
          <div id="linkNav">
            <% if logado? %>
                <%= render 'layouts/user_navbar' %>    
            <% elsif paciente_logado? %>
                <%= render 'layouts/paciente_navbar' %>
            <%end%>
          </div>
        </ul>
      </div>
    </nav>
    <div class="col s6 offset-s3">
      <div>
        <div>
          <% if notice.present? %>
            <p id="notice"><%= notice %> </p>
          <% end %>
          <% if alert.present? %>
           <p id="alert"><%= alert %> </p>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  <% if logado? && usuario_atual.nivel == 'auxiliar' %>
    <div class="fixed-action-btn">
      <a class="btn-floating btn-large">
        <i class="fa fa-pencil" aria-hidden="true"></i>
      </a>
      <ul>
        <li><%= link_to '<i class="fa fa-home" aria-hidden="true" title="Lista de Consultas"></i>'.html_safe,
        lista_consultas_path, class: "btn-floating yellow darken-1" %></li>
        <li><%= link_to '<i class="fa fa-user-md" aria-hidden="true" title="Consultas"></i>'.html_safe,
        consultas_path, class: "btn-floating blue" %></li>
        <li><%= link_to '<i class="fa fa-user-circle" aria-hidden="true" title="Paciente"></i>'.html_safe,
        pacientes_path, class: "btn-floating green" %></li>
        <li><%= link_to '<i class="fa fa-user-plus" aria-hidden="true" title="Novo Paciente"></i>'.html_safe,
        new_paciente_path, class: "btn-floating red" %></li>
      </ul>
    </div>
  <% end %>
</body>
</html>